### ISSUE TITLE
Add option to disable uprating.

### ISSUE THREAD

**Issue by CalebPena** [PolicyEngine/policyengine-household-api#386]
Uprating can lead to bugs for programs trying to calculate the current benefit value.

**Comment by anth-volk** [comment]
Could you give a bit more detail and/or an example of where this goes wrong?

**Comment by MaxGhenis** [comment]
Let's fix this in the country packages by removing uprating in cases where it doesn't apply. If we identify reasons other than inaccuracies in the country packages then we can reopen this.
